# Generated by Django 5.1.1 on 2024-09-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway_system.timetable')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Броні',
            },
        ),
    ]
